### ISSUE TITLE
Debian build for Python 3.11 fails

### ISSUE THREAD

**Issue by olebole** [lofar-astron/PyBDSF#189]
This is a forward of [Debian#1024499](https://bugs.debian.org/1024499):

When trying to build the package for Python 3.11, the build fails with the following error when trying to import bdsf:
```
ERROR: bdsf (unittest.loader._FailedTest.bdsf)
----------------------------------------------------------------------
ImportError: Failed to import test module: bdsf
Traceback (most recent call last):
  File "/usr/lib/python3.11/unittest/loader.py", line 440, in _find_test_path
    package = self._get_module_from_name(name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11/build/bdsf/__init__.py", line 21, in <module>
    from .collapse import Op_collapse
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11/build/bdsf/collapse.py", line 11, in <module>
    from . import _cbdsm
SystemError: initialization of _cbdsm raised unreported exception
```
This happens on all our platforms. I have no idea why this "unreported exception" is raised. Full build log for x86_64 is [here](https://buildd.debian.org/status/fetch.php?pkg=pybdsf&arch=amd64&ver=1.10.1-1%2Bb3&stamp=1668731964&raw=0).

Any idea what this could be?

**Comment by olebole** [comment]
I now tried it manually with Python 3.10; however I even then run into errors:
```
$ python3 -m pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/oles/Projects/2011/debian/python/pybdsf
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-falzomfu/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-falzomfu/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-falzomfu/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 483, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-falzomfu/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
        File "/tmp/pip-build-env-falzomfu/overlay/local/lib/python3.10/dist-packages/numpy/distutils/__init__.py", line 24, in <module>
          from . import ccompiler
        File "/tmp/pip-build-env-falzomfu/overlay/local/lib/python3.10/dist-packages/numpy/distutils/ccompiler.py", line 20, in <module>
          from numpy.distutils import log
        File "/tmp/pip-build-env-falzomfu/overlay/local/lib/python3.10/dist-packages/numpy/distutils/log.py", line 4, in <module>
          from distutils.log import Log as old_Log
      ImportError: cannot import name 'Log' from 'distutils.log' (/tmp/pip-build-env-falzomfu/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/log.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
This happens both with version 1.10.1 and the current master. My system is Debian "testing",

* Python 3.10.8
* setuptools 65.5.0
* distutils 3.10.8
* numpy 1.23.2
* pep517 0.13.0

**Comment by gmloose** [comment]
I usually don't build Python wheels on Linux directly, because they're almost useless for release purposes. I always use Docker `manylinux` images to build those wheels. I'm not sure why you would want to build wheels as a Debian packager.

**Comment by olebole** [comment]
I don't want to build wheels; I just figure out the problems with Python 3.11; and the first step is to try a regular build with Python 3.10, as described in the README (which explicitly describes the installation via "pip install ."). And this leads already to problems. Once these are solved, I would check what exactly the difference between this build and a build with Python 3.11 is and so come closer to the issue (and its solution).

**Comment by gmloose** [comment]
OK, I can reproduce the issue. It is caused by recent changes to `setuptools`. See https://github.com/numpy/numpy/issues/22623 for more information. I will fix PyBDSF `master` asap. Maybe you can backport the fix, if you want to the latest released version.

**Comment by gmloose** [comment]
@olebole, can you please check if this also resolves the issue for you?

**Comment by olebole** [comment]
This doesn't work for me, since I am bound to the package versions provided by Debian.

**Comment by gmloose** [comment]
I thought that Debian provided a means to patch source files, before building and packaging?

**Comment by olebole** [comment]
The change in #190 just puts a restriction on the setuptools version (<65.6); however this is already fulfilled with the setuptools version provided by Debian (65.5.0). Or do I miss something here?

**Comment by gmloose** [comment]
As far as I know, `pip` creates a sand-box environment to do the build and install. It uses the version of `setuptools` specified in the `pyproject.toml` file. So, if you don't constrain the version there, it will pull in the latest `setuptools`.

**Comment by olebole** [comment]
I can confirm that this works, so this would be a base for to continue here for the Py 3.11 problem. Thanks.

**Comment by gmloose** [comment]
OK, thanks. Then I'll close this issue.

**Comment by olebole** [comment]
Hmm, the Python 3.11 issue is still not solved I think. Since we (and the world) are moving towards the new Python version, it would be good to get it working, even if you don't support it in the moment.

**Comment by gmloose** [comment]
OK, I'll reopen the issue, and have a second look. Now for Python 3.11

**Comment by gmloose** [comment]
For Python 3.11 I run into a completely different problem. It still doesn't build, but the problem is in no way related to the reported problem.
```
Traceback (most recent call last):
  File "/PyBDSF/./setup.py", line 290, in <module>
Reading fortran codes...
	Reading file 'src/fortran/pytess_simple.f' (format:fix,strict)
	Reading file 'src/fortran/pytess_roundness.f' (format:fix,strict)
	Reading file 'src/fortran/constants.inc' (format:fix)
Line #6 in src/fortran/constants.inc:"        parameter (fwsig=2.35482d0) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Line #7 in src/fortran/constants.inc:"        parameter (rad=57.29577951308232) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Line #7 in src/fortran/constants.inc:"        parameter (rad=57.29577951308232) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Line #8 in src/fortran/constants.inc:"        parameter (c=2.99792458d8) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Line #8 in src/fortran/constants.inc:"        parameter (c=2.99792458d8) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Line #8 in src/fortran/constants.inc:"        parameter (c=2.99792458d8) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Line #9 in src/fortran/constants.inc:"        parameter (bolt=1.3806505d-23) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Line #9 in src/fortran/constants.inc:"        parameter (bolt=1.3806505d-23) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Line #9 in src/fortran/constants.inc:"        parameter (bolt=1.3806505d-23) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Line #9 in src/fortran/constants.inc:"        parameter (bolt=1.3806505d-23) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Post-processing...
	Block: _pytesselate
			Block: pytess_simple
		Block: pytess_roundness
		Block: tess_bin_complicated
	Block: calc_area_tess
	Block: tile_roundness
In: src/fortran/pytess_roundness.f:tile_roundness
get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
In: src/fortran/pytess_roundness.f:tile_roundness
get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
In: src/fortran/pytess_roundness.f:tile_roundness
get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
In: src/fortran/pytess_roundness.f:tile_roundness
get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
In: src/fortran/pytess_roundness.f:tile_roundness
get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
In: src/fortran/pytess_roundness.f:tile_roundness
get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
Post-processing (stage 2)...
    main()
  File "/PyBDSF/./setup.py", line 248, in main
    setup(
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/PyBDSF/./setup.py", line 95, in run
    numpy_build_ext.run(self)
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/numpy/distutils/command/build_ext.py", line 101, in run
    self.run_command('build_src')
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 144, in run
    self.build_sources()
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 161, in build_sources
    self.build_extension_sources(ext)
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 321, in build_extension_sources
    sources = self.f2py_sources(sources, ext)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/numpy/distutils/command/build_src.py", line 562, in f2py_sources
    numpy.f2py.run_main(f2py_options + ['--lower',
  File "/opt/python/cp311-cp311/lib/python3.11/site-packages/numpy/f2py/f2py2e.py", line 469, in run_main
    raise TypeError('All blocks must be python module blocks but got %s' % (
TypeError: All blocks must be python module blocks but got 'subroutine'
The command '/bin/sh -c /opt/python/${TARGET}/bin/python ./setup.py build_ext -j${THREADS}' returned a non-zero code: 1
```

**Comment by gmloose** [comment]
This problem is introduced with numpy 1.23, which is the oldest supported version for Python 3.11. If I downgrade numpy to 1.22.4 and build the wheel locally, then the build succeeds. This, however, is not a sustainable solution, because numpy < 1.23 is not officially supported for Python 3.11

**Comment by gmloose** [comment]
I stumbled upon a solution to this when trying out `scikit-build`. I have no clue why exactly this works, but if I swap the two lines:
```
           "src/fortran/pytess_simple.f",
           "src/fortran/pytess_roundness.f"
```
and put them in alphabetical order (don't think that's relevant), then the build succeeds. I'll create a new pull request for @olebole to test.

**Comment by gmloose** [comment]
@olebole, can you try out #205?

**Comment by olebole** [comment]
I can confirm that the build succeeds after applying #205 to 1.10.3a2.

**Comment by gmloose** [comment]
> This problem is introduced with `numpy` 1.23, which is the oldest supported version for Python 3.11. If I downgrade `numpy` to 1.22.4 and build the wheel locally, then the build succeeds. This, however, is not a viable solution, because `numpy` < 1.23 is not officially supported for Python 3.11.
> 
> When you install `bdsf` from the wheel that was generated with `numpy` 1.22.4, it will pull `numpy` 1.23.5 from PyPI, and this will cause the following error if you try to import `bdsf`:
> 
> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/local/lib/python3.11/site-packages/bdsf/__init__.py", line 21, in <module>
>     from .collapse import Op_collapse
>   File "/usr/local/lib/python3.11/site-packages/bdsf/collapse.py", line 11, in <module>
>     from . import _cbdsm
> SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function
> ```

This error is caused by https://github.com/boostorg/python/issues/400 (Python 3.11 gives SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function). 

For Python 3.11 we need to use Boost >= 1.81
