### ISSUE TITLE
Wheel fails to build using GCC version 7 and above (ubuntu 20.04)

### ISSUE THREAD

**Issue by bennahugo** [lofar-astron/PyBDSF#167]
Having an issue building from source using GCC v7 and v9 respectively. Best I can tell from the log the following is not declared:
```
    In file included from natgrid/Src/natgrid.c:6:
    natgrid/Include/nnmhead.h:43:28: error: ‘_IO_stderr’ undeclared here (not in a function); did you mean ‘stderr’?
       43 | FILE    *fopen(), *filee = _IO_stderr;
```
The rest are just warnings as far as I can tell. By the looks of it the wheels are being build with an ancient version of gcc (4.7) -- manylinux2010_x86_64
```
Installing:
 gcc-gfortran                    x86_64                    4.4.7-23.el6                         base                    4.7 M
Installing for dependencies:
 cloog-ppl                       x86_64                    0.15.7-1.2.el6                       base                     93 k
 cpp                             x86_64                    4.4.7-23.el6                         base                    3.7 M
 gcc                             x86_64                    4.4.7-23.el6                         base                     10 M
 libgfortran                     x86_64                    4.4.7-23.el6                         base                    268 k
 ppl                             x86_64                    0.10.2-11.el6                        base                    1.3 M
```

**Comment by bennahugo** [comment]
I should add this is specifically when pulling the last release from pypi. I'm testing against master now to see if there is any changes

**Comment by gmloose** [comment]
I'm not sure I completely understand what you're trying to do. The recommended way to build portable binary wheels is to use the `manylinux` solution. It _purposely_ uses an old GCC compiler to ensure maximum portability. How exactly are you building the software on your machine?

**Comment by bennahugo** [comment]
@gmloose I'm running ```pip install --no-binary bdsf bdsf``` in order to build against an older version of numpy within a 3.8 virtual environment, because I'm getting a Numpy multiarray ABI error with the distributed wheel when trying to use v0,19. I'm looking at the code at the moment to see what changes to make to get it compiling with GNU v9

**Comment by gmloose** [comment]
I think the latest release (1.9.2) is too old. I created a docker container based on Ubuntu 20.04. If I then use `master` and run `pip install --no-binary bdsf .` (i.e. use current directory(`.`), instead of download latest from PyPI (`bdsf`), I get a different error. If I then fix `setup.py`, by adding `Extension` to `from numpy.distutils.core import ` it builds successfully, locally. Haven't tried to run it, though.

**Comment by bennahugo** [comment]
@gmloose I've also come to the conclusion that the pypi sdist is too old. I can get it to build when running python setup.py build (or install) using GCC v7 and v9. When I add Extension to the imports it seems to build, however it still binds to the system numpy version. When running python setup.py install it seemingly builds against the virtualenv numpy, so I'm not sure where the difference stems from here. I'm going to close the issue as it is already fixed in master, but will it be possible to make a sdist and bdist release for the latest code in master?

**Comment by gmloose** [comment]
Yes, we plan to make a new release in the upcoming months. But we need to find the time to do so.
